language: shell
dist: trusty
sudo: required

services:
  - docker

notifications:
  slack: myaegee:jhn0jBOynuYf93wsSfJI1XQk

before_script:
    - cd docker
    - sudo docker network create OMS
    - export MYAEGEE_ENV=development; export PW_POSTGRES=postgres; export PATH_OMS_CORE_ELIXIR=.;
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml -f docker-compose.dev.yml build
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml -f docker-compose.dev.yml up -d
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml -f docker-compose.dev.yml logs -f oms-core-elixir &
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml -f docker-compose.dev.yml exec oms-core-elixir ash /usr/src/scripts/wait.sh


script:
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml -f docker-compose.dev.yml exec oms-core-elixir env MIX_ENV=test mix coveralls
