language: shell
dist: trusty
sudo: required

services:
  - docker

before_script:
    - cd docker
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml build
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml up -d
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml logs -f oms-core-elixir &
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml exec oms-core-elixir ash /usr/src/scripts/wait.sh


script:
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml exec -e MIX_ENV=test oms-core-elixir mix coveralls
