FROM elixir:1.8-alpine

RUN mkdir -p /usr/src/myapp \
	&& mkdir -p /usr/src/scripts \
	&& mix local.hex --force \
  && mix local.rebar --force \
	&& apk add --update --no-cache nodejs nodejs-npm make gcc g++

WORKDIR /usr/src/myapp

COPY mix.exs /usr/src/myapp/mix.exs
RUN ["mix", "deps.get"]

COPY . /usr/src/myapp/

ENV MIX_ENV=prod
ENV PORT=4000
RUN ["mix", "compile"]

EXPOSE ${PORT}

COPY bootstrap.sh /usr/src/scripts/bootstrap.sh
COPY wait.sh /usr/src/scripts/wait.sh

CMD ash /usr/src/scripts/bootstrap.sh \
      && mix phx.server
